[manager]
linemode = "size_and_mtime"

[plugin]
prepend_fetchers = [
{ id = "git", name = "*", run = "git" },
{ id = "git", name = "*/", run = "git" },
]
prepend_previewers = [
{ mime = "application/epub+zip", run = "epub-preview" },
]

[opener] 
edit = [
{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
{ run = 'xdg-open "$@"', desc = "Open" },
]
zathura-open = [
{ run = 'zathura "$@"', desc = "Open with zathura" }, 
]

[open]
prepend_rules = [
{ name = "*.cbz", use = "zathura-open" },
]
